[tool.poetry]
name = "pyeasycmdline"
version = "1.0.0-rc.2"
description = "A YAML-driven command-line interface framework"
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"
packages = [{include = "easycmdline"}]

[tool.poetry.dependencies]
python = "^3.9"
pyyaml = "^6.0"
black = "^25.1.0"
flake8 = "^7.2.0"
pylint = "^3.3.7"
python-semantic-release = "^10.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0"
pytest-mock = "^3.10"
mypy = "^1.15.0"
types-pyyaml = "^6.0.12.20250402"
pytest-cov = "^6.1.1"
python-semantic-release = "^10.0.0"


[tool.poetry.scripts]
easycmdline = "easycmdline.cli:run"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pylint]
ignore = ["tests", "easycmdline/tests"]
ignore-patterns = ["test_.*\\.py"]
max-line-length = 120
disable = [
    "missing-module-docstring",
    "missing-class-docstring", 
    "missing-function-docstring",
    "too-few-public-methods",
    "protected-access",
    "redefined-outer-name",
    "import-outside-toplevel",
    "unused-argument",
    "broad-exception-caught"
]

[tool.semantic_release]
version_variables = ["easycmdline/__init__.py:__version__"]
version_toml = ["pyproject.toml:tool.poetry.version"]
upload_to_vcs_release = true
build_command = "poetry build"
major_on_zero = false
tag_format = "v{version}"

[tool.semantic_release.branches.main]
match = "main"
prerelease = false

[tool.semantic_release.branches.release]
match = "release/.*"
prerelease = true
prerelease_token = "rc"

[tool.semantic_release.publish]
dist_glob_patterns = ["dist/*"]
upload_to_vcs_release = true
upload_to_release = true

[tool.semantic_release.remote]
name = "origin"
type = "github"
ignore_token_for_push = false
