# release.yml
name: Release Workflow

on:
  push:
    branches:
      - "release/*"
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  tests-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - run: make dev-install
      - run: make lint
      - run: make test
      - run: make coverage

  create-rc-tag:
    if: startsWith(github.ref, 'refs/heads/release/')
    needs: tests-and-coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create RC Tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          RELEASE_BRANCH=${GITHUB_REF#refs/heads/release/}
          LAST_TAG=$(git tag -l "v$RELEASE_BRANCH-rc.*" --sort=-v:refname | head -n1)

          if [[ -z "$LAST_TAG" ]]; then
              NEW_TAG="v${RELEASE_BRANCH}-rc.1"
          else
              RC_NUMBER=$(echo $LAST_TAG | grep -oE '[0-9]+$')
              NEW_RC_NUMBER=$((RC_NUMBER+1))
              NEW_TAG="v${RELEASE_BRANCH}-rc.$NEW_RC_NUMBER"
          fi

          git tag -a $NEW_TAG -m "Auto RC tag $NEW_TAG"
          git push origin $NEW_TAG

  semantic-release:
    if: github.ref == 'refs/heads/main'
    needs: tests-and-coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: make dev-install

      - name: Run Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry run semantic-release publish

      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry publish --build --no-interaction
